# Generated by Django 5.0.2 on 2024-02-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_companyprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='country',
        ),
    ]
