# Generated by Django 5.0.2 on 2024-02-12 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_companyprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.FileField(upload_to='company/adhar')),
                ('liscence', models.FileField(upload_to='company/liscence')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_documents', to='users.companyprofile')),
            ],
        ),
    ]
