# Generated by Django 5.0.2 on 2024-02-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_companydocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocuments',
            name='adhar_card',
            field=models.FileField(null=True, upload_to='company/adhar'),
        ),
        migrations.AlterField(
            model_name='companydocuments',
            name='liscence',
            field=models.FileField(null=True, upload_to='company/liscence'),
        ),
    ]
