# Generated by Django 5.0.2 on 2024-02-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/profile'),
        ),
    ]
