# Generated by Django 5.0.2 on 2024-02-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobtype_workerprofile_jobprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobprofile',
            name='job_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='job/profile'),
        ),
    ]
