# Generated by Django 5.0.2 on 2024-02-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_jobprofile_job_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobprofile',
            old_name='is_negotialble',
            new_name='is_negotiable',
        ),
    ]
