# Generated by Django 5.0.2 on 2024-02-21 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('users', '0009_customerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=10)),
                ('street_name', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('land_mark', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customerprofile')),
            ],
        ),
    ]
