# Generated by Django 5.0.2 on 2024-02-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_orderaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street_name',
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
