# Generated by Django 5.0.2 on 2024-02-21 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_address_street_name_address_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
