# Generated by Django 5.0.2 on 2024-02-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_address_house_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
