# Generated by Django 5.0.2 on 2024-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_pin_code_orderaddress_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='street_name',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
