# Generated by Django 5.0.2 on 2024-02-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_orderaddress_street_name_orderaddress_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], max_length=25, null=True),
        ),
    ]
