# Generated by Django 5.0.2 on 2024-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_orderaddress_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/product'),
        ),
    ]
