# Generated by Django 5.0.2 on 2024-02-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=60, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=30, null=True)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Online', 'Online')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Un_Paid', 'Unpaid')], max_length=10)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
