# Generated by Django 5.0.2 on 2024-02-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='transaction_id',
            new_name='online_transaction_id',
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Un_Paid', 'Unpaid')], default='Un_Paid', max_length=10),
        ),
    ]
